let rand_char_j = 0
let rand_char_i = 0
let country_list = [
"australia",
"brazil",
"canada",
"denmark",
"egypt",
"finland",
"germany",
"hungary",
"iceland",
"japan",
"kuwait",
"luxembourg",
"mongolia",
"nepal",
"oman",
"pakistan",
"qatar",
"russia",
"sweden",
"thailand",
"america",
"vietnam",
"yemen",
"zimbabwe",
"newzealand",
"spain",
"turkey",
"peru",
"portugal",
"srilanka",
"madagascar",
"papuanewguinea",
"tonga",
"fiji",
"indonesia",
"india",
"argentina",
"phillipines",
"ukraine",
"vaticancity",
"myanmar",
"laos",
"tuvalu",
"vanuatu",
"venezuela",
"paraguay",
"guyana",
"poland",
"kyrgyzstan",
"northkorea",
"southkorea",
"micronesia",
"algeria",
"chile",
"colombia",
"cuba",
"bangladesh",
"china",
"arabemerites",
"turkmenistan",
"iran",
"iraq",
"saudiarabia",
"england",
"ireland",
"norway",
"southafrica",
"zambia",
"lesotho",
"malawi"
]
let random_country = randint(0, 69)
let randdom_country_name = country_list[random_country]
story.printText(randdom_country_name, 0, 0)
for (let index = 0; index < 1; index++) {
    rand_char_i = randint(0, randdom_country_name.length - 1)
    rand_char_j = randint(0, randdom_country_name.length - 1)
    randdom_country_name[rand_char_j] = "this".charAt(rand_char_i)
    info.setScore(rand_char_i)
}
